# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-aath0-github-io'

google-ID: 'UA-103680525-1'

menu:
- {name: 'Research', path: 'https://aath0.github.io/menu', url: 'research.html'}
- {name: 'People', path: 'https://aath0.github.io/menu', url: 'people.html'}
- {name: 'Publications', path: 'https://aath0.github.io/menu', url: 'publications.html'}
- {name: 'News', path: 'https://aath0.github.io/menu', url: 'news.html'}
- {name: 'Meetings', path: 'https://aath0.github.io/menu', url: 'schedule.html'}
- {name: 'Resource', path: 'https://aath0.github.io/AlgorithmsNeuroscience/Tutorial_files/Introduction', url: ''}
- {name: 'Positions', path: 'https://aath0.github.io/menu', url: 'announcement.html'}
- {name: 'Contact', path: 'https://aath0.github.io/menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/aath0'}
- {icon: 'twitter', link: 'https://www.twitter.com/aath0'}
- {icon: 'envelope', link: 'mailto:athina.tz@gmail.com'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: ' '

post_date_prefix: 'Written on'
